name: 'Validate KFP Compiled Files'
description: 'Validates if the changed Kubeflow Pipelines .py files were compiled'
branding:
  icon: 'check'
  color: 'blue'
inputs:
  pipelines-map-file:
    description: 'The file with the mapping from .py to .yaml'
    required: true
  requirements-file:
    description: 'The requirements.txt file'
    required: true
  extra-compile-args:
    description: 'Extra arguments to pass to kfp dsl compile (optional)'
    required: false
runs:
  using: "composite"
  steps:
    - name: Install Python dependencies
      shell: bash
      run: pip install -r ${{ inputs.requirements-file }}

    - name: Install jq (for JSON parsing)
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Verify compiled pipelines
      shell: bash
      run: $GITHUB_ACTION_PATH/verify_kfp_compiled.sh ${{ inputs.pipelines-map-file }} ${{ inputs.extra-compile-args || '' }}
